# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Load Balancer Node
  config.vm.define "df-loadbalancer" do |lb|
    lb.vm.box = "generic/ubuntu2204"
    lb.vm.hostname = "df-loadbalancer"
    lb.vm.network "private_network", ip: "172.16.16.100"
    lb.vm.provider "virtualbox" do |v|
      v.gui = true
      v.name = "df-loadbalancer"
      v.memory = 2048
      v.cpus = 1
    end
  end

  MasterCount = 2
 
  # Kubernetes Master Nodes
  (1..MasterCount).each do |i|
    config.vm.define "df-k8s-master-#{i}" do |masternode|
      masternode.vm.box = "generic/ubuntu2204"
      masternode.vm.hostname = "df-k8s-master-#{i}"
      masternode.vm.network "private_network", ip: "172.16.16.10#{i}"
      masternode.vm.provider "virtualbox" do |v|
        v.gui = true
        v.name = "df-k8s-master-#{i}"
        v.memory = 2048
        v.cpus = 2
      end
    end
  end

  NodeCount = 2

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "df-k8s-node-#{i}" do |workernode|
      workernode.vm.box = "generic/ubuntu2204"
      workernode.vm.hostname = "df-k8s-node-#{i}"
      workernode.vm.network "private_network", ip: "172.16.16.20#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.gui = true
        v.name = "df-k8s-node-#{i}"
        v.memory = 4096
        v.cpus = 1
      end
    end
  end

end
